# Clove MVP Configuration Example
# Copy this file to config.yaml and fill in your values

# Server configuration
server:
  host: '0.0.0.0'
  port: 4000

# Logger configuration
logger:
  level: 'info' # debug, info, warn, error
  format: 'text' # json or text

# API key for protecting the proxy endpoints
auth:
  api_key: 'your-secret-api-key-here'

# OAuth 2.0 configuration for Claude authentication
# Note: organization_uuid is passed as a query parameter, not in the path
# Environment variables:
#   OAUTH_AUTHORIZE_URL - OAuth authorization endpoint URL
#   OAUTH_TOKEN_URL - OAuth token exchange endpoint URL
#   OAUTH_REDIRECT_URI - OAuth redirect URI for authorization flow
#   OAUTH_SCOPE - OAuth scopes (space-separated)
oauth:
  client_id: 'your-claude-oauth-client-id'
  authorize_url: 'https://claude.ai/oauth/authorize'
  token_url: 'https://console.anthropic.com/v1/oauth/token'
  redirect_uri: 'https://console.anthropic.com/oauth/code/callback'
  scope: 'user:profile user:inference'

# Claude API configuration
claude:
  base_url: 'https://api.anthropic.com'

# Storage configuration
storage:
  data_folder: '~/.clove/data'

# Retry configuration
retry:
  max_retries: 3
  retry_delay: 1s
