# Claude Proxy Configuration Example
# Copy this file to config.yaml and fill in your values

# Server configuration
server:
  host: '0.0.0.0'
  port: 4000
  # Request timeout for proxying to Claude API
  # Recommended: 5m for extended thinking, streaming responses, and long generations
  # Can be adjusted based on your use case (e.g., 2m for faster responses, 10m for very long tasks)
  request_timeout: 5m  # Valid units: s (seconds), m (minutes), h (hours)

# Logger configuration
logger:
  level: 'info' # debug, info, warn, error
  format: 'text' # json or text

# API key for protecting the proxy endpoints
auth:
  api_key: '667788'

# OAuth 2.0 configuration for Claude authentication
# Note: organization_uuid is passed as a query parameter, not in the path
# Environment variables:
#   OAUTH_AUTHORIZE_URL - OAuth authorization endpoint URL
#   OAUTH_TOKEN_URL - OAuth token exchange endpoint URL
#   OAUTH_REDIRECT_URI - OAuth redirect URI for authorization flow
#   OAUTH_SCOPE - OAuth scopes (space-separated)
oauth:
  client_id: '9d1c250a-e61b-44d9-88ed-5944d1962f5e'
  authorize_url: 'https://claude.ai/oauth/authorize'
  token_url: 'https://console.anthropic.com/v1/oauth/token'
  redirect_uri: 'https://console.anthropic.com/oauth/code/callback'
  scope: 'user:profile user:inference'

# Claude API configuration
# Using Claude.ai web API (compatible with OAuth tokens)
# For public API, use: https://api.anthropic.com
claude:
  base_url: 'https://api.anthropic.com'

# Storage configuration
storage:
  data_folder: '/data'

# Retry configuration
retry:
  max_retries: 3
  retry_delay: 1s
