server:
  host: 'localhost'
  port: 4000

logger:
  level: 'debug'
  format: 'text'

telegram:
  enabled: false # Set to true to enable Telegram notifications
  bot_token: 'YOUR_BOT_TOKEN_HERE' # Get from @BotFather on Telegram
  chat_id: 'YOUR_CHAT_ID_HERE' # Your Telegram chat ID
  timeout: 10s
